/**
 * GENERATED from the server's own /openapi.json. Regenerate with:
 *
 *     uv run satisfactory-mcp-web          # terminal 1
 *     npm run typegen                      # terminal 2, in this directory
 *
 * Committed on purpose: it is the checked-in record of the API this page was built
 * against, so a diff here is the server's surface changing and is worth reading. It is
 * also why `npm run check` needs no running server.
 *
 * READ WHAT THIS DOES AND DOES NOT SAY. Every endpoint in `interfaces/web/api.py` is
 * annotated `-> dict` and publishes no response schema, so almost every `200` below is
 * `unknown`. What this file is authoritative for is the other half: which paths exist,
 * which query parameters each takes, and what a validation error looks like. The rest of
 * the response bodies are declared by hand in `api-types.ts`, from observed payloads, and
 * that file says so at the top.
 *
 * ONE EXCEPTION, and it is the direction of travel: `/api/floors` declares a response
 * model, so its whole body IS described here -- `FloorsResponse` and the six schemas under
 * it. A client for the floor view should read them from this file and add nothing to
 * `api-types.ts`; the point of doing that endpoint first is that it has no client yet, so
 * there was no observed interface to reconcile with.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Worlds
         * @description Every world the save directory holds, newest first.
         */
        get: operations["worlds_api_worlds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nodes
         * @description The resource node table, joined to what this save has built on it.
         *
         *     The join is deliberately partial and says so: ``occupancy`` resolves only the
         *     extractors whose target is a node key, so ``occupied`` false means "no extractor
         *     known here", never "free". The map draws it as unknown-or-free and the popup
         *     carries the node id, which doubles as a ``node:`` selector for the MCP tools.
         *
         *     The region name is joined here rather than in the browser because the raster lives on
         *     this side: sending 608 rows and then a 30x30 grid for the page to index into would put
         *     the orientation trap (row 0 is the NORTH edge) in two places. ``label_for_node`` rather
         *     than ``label_for`` -- it prefers the hand-verified override table, so the nodes someone
         *     actually checked come back as ``verified`` instead of as a 256 m cell's best guess.
         *     ``null`` for a node the raster calls void, which is the honest answer for the handful
         *     that sit on islands off the grid.
         *
         *     **A failed save is not a failed answer** -- the same rule ``/api/inspect`` already
         *     follows, because the two used to disagree: the node table is static and needs no
         *     ``.sav``, so a world whose save will not load still gets its geography. What it loses
         *     is the occupancy join, and ``save_error`` says so out loud (with ``occupied`` null at
         *     the top, since "0 of them occupied" would be a claim no one measured).
         */
        get: operations["nodes_api_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect
         * @description What is at a coordinate: the region, the measured ground, and the nearest nodes.
         *
         *     The three answers a site starts with, and none of them was on the map before. Every
         *     one comes straight out of ``domain.spatial`` -- this endpoint converts metres to the
         *     save's centimetres, calls three functions, and rounds.
         *
         *     **A failed save is not a failed answer.** The node table is static, covers the whole
         *     map and needs no ``.sav`` at all, so a world whose save will not load still gets its
         *     region, its ground elevation and its nearest nodes; what it loses is the built
         *     population and the occupancy join, and ``save_error`` says so out loud rather than
         *     letting "no extractor here" quietly mean "no save here".
         *
         *     **And it prefers the extracted terrain when there is any.** On a machine where
         *     ``tools/gen_world_heightmap.py`` has been run, the 1 m field answers "how high is it
         *     here" for unexplored ground with one number at the coordinate asked about, instead of a
         *     population of things standing near it -- and it says which layer of itself answered, so
         *     a 0.2 m landscape reading and a 3.9 m fill reading are told apart. Where there is no
         *     field, or the field has no data there, this is exactly the endpoint it was before.
         *
         *     Not cached, deliberately and by measurement: ``sample_points`` over the 320-hour
         *     reference world builds 9,525 samples in 2.0 ms and ``probe`` scans them in 0.8 ms, so
         *     a per-(world, save) cache would add an invalidation bug to save ~3 ms on a click. The
         *     field is cached, because it is 0.45 s of zlib and 170 MB either way -- but by the
         *     loader, keyed on its own sidecar's mtime, so this endpoint stays a caller.
         */
        get: operations["inspect_api_inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regions
         * @description The biome raster: a 30x30 character grid, its legend, and each region's extent.
         *
         *     No ``?save``/``?world``: this is the world's own geography, identical for every save,
         *     which is why it is cacheable and fetched once per page load.
         *
         *     The raster comes through ``domain.spatial.regions``, which reads
         *     ``data/region_names.json``. Two committed files carry a 30x30 grid and they differ:
         *     this one is the file whose per-region bounding boxes are derived from its own grid, so
         *     every cell provably lies inside the box of the region it names -- which is exactly
         *     what the drawing client is checked against. ``satisfactory_regions.json``'s boxes come
         *     from a coarser 1.024 km grid and do not agree with its raster cell for cell, so
         *     painting from it would leave nothing to verify orientation with.
         *
         *     The one thing a drawing client gets wrong is orientation, so it is stated here rather
         *     than left to be inferred. Game +X is east and game **+Y is south**; ``y0_m`` is the
         *     smallest y, so **grid row 0 is the northern edge** and column 0 the western one. Cell
         *     ``(i, j)`` spans x ``[x0_m + i*cell_m, x0_m + (i+1)*cell_m]`` and y ``[y0_m + j*cell_m,
         *     ...]``, and a page that plots ``[-y, x]`` has to flip those y bounds to draw it. The
         *     ``.`` cells are ocean or off-map and carry no name: left unpainted they are the
         *     coastline.
         */
        get: operations["regions_api_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mapimage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mapimage
         * @description A map render the *user* dropped in, if they dropped one in. Never shipped.
         *
         *     HEAD is routed alongside GET on purpose: the page probes with HEAD before it builds
         *     an ``imageOverlay``, and FastAPI -- unlike bare Starlette -- does not add HEAD to a
         *     GET route by itself, so a probe would come back 405 and read as "no image".
         *
         *     An absent file is the *expected* state, so the HEAD probe answers **204**, not 404:
         *     a 404 is logged red in every devtools console on every clean page load, which trains
         *     the reader to ignore console errors on this page. The GET keeps its 404 with the
         *     where-to-put-it message -- anything actually fetching the bytes deserves the reason.
         *
         *     The corners travel with the file in ``X-Map-Bounds-M`` (``x_min,y_min,x_max,y_max``,
         *     metres, game axes) so the one probe the page already makes answers both questions.
         */
        get: operations["mapimage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Mapimage
         * @description A map render the *user* dropped in, if they dropped one in. Never shipped.
         *
         *     HEAD is routed alongside GET on purpose: the page probes with HEAD before it builds
         *     an ``imageOverlay``, and FastAPI -- unlike bare Starlette -- does not add HEAD to a
         *     GET route by itself, so a probe would come back 405 and read as "no image".
         *
         *     An absent file is the *expected* state, so the HEAD probe answers **204**, not 404:
         *     a 404 is logged red in every devtools console on every clean page load, which trains
         *     the reader to ignore console errors on this page. The GET keeps its 404 with the
         *     where-to-put-it message -- anything actually fetching the bytes deserves the reason.
         *
         *     The corners travel with the file in ``X-Map-Bounds-M`` (``x_min,y_min,x_max,y_max``,
         *     metres, game axes) so the one probe the page already makes answers both questions.
         */
        head: operations["mapimage"];
        patch?: never;
        trace?: never;
    };
    "/api/maptiles/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Maptiles
         * @description The artwork pyramid, at the URL it has always had. An alias for ``map``.
         *
         *     Kept because it is live: every cached tile, every bookmark and the page as it stands
         *     all address the base map here, and a route that moved would break all three to say the
         *     same thing one segment longer. So this is not a redirect and not a deprecation -- it is
         *     the default layer's name being optional, and it answers byte for byte and header for
         *     header what ``/api/maptiles/map/{z}/{x}/{y}`` answers.
         */
        get: operations["maptiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Maptiles
         * @description The artwork pyramid, at the URL it has always had. An alias for ``map``.
         *
         *     Kept because it is live: every cached tile, every bookmark and the page as it stands
         *     all address the base map here, and a route that moved would break all three to say the
         *     same thing one segment longer. So this is not a redirect and not a deprecation -- it is
         *     the default layer's name being optional, and it answers byte for byte and header for
         *     header what ``/api/maptiles/map/{z}/{x}/{y}`` answers.
         */
        head: operations["maptiles"];
        patch?: never;
        trace?: never;
    };
    "/api/maptiles/{layer}/{z}/{x}/{y}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Maptiles Layer
         * @description One tile of a named base layer: ``map``, ``terrain`` or ``satellite``.
         *
         *     Four segments where the alias above has three, so the two routes cannot collide: a
         *     three-segment path has no layer to name and is the artwork by definition.
         *
         *     An unknown layer is a 404 that lists the ones there are, rather than a 422 about a path
         *     parameter. The distinction is the reader's: asking for a layer this build does not have
         *     is asking for a picture that is not there, which is the same answer as asking for a tile
         *     of one that has not been generated -- and a page that probes for layers it might find
         *     deserves to be told which names exist rather than which types were expected.
         */
        get: operations["maptiles_layer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Maptiles Layer
         * @description One tile of a named base layer: ``map``, ``terrain`` or ``satellite``.
         *
         *     Four segments where the alias above has three, so the two routes cannot collide: a
         *     three-segment path has no layer to name and is the artwork by definition.
         *
         *     An unknown layer is a 404 that lists the ones there are, rather than a 422 about a path
         *     parameter. The distinction is the reader's: asking for a layer this build does not have
         *     is asking for a picture that is not there, which is the same answer as asking for a tile
         *     of one that has not been generated -- and a page that probes for layers it might find
         *     deserves to be told which names exist rather than which types were expected.
         */
        head: operations["maptiles_layer"];
        patch?: never;
        trace?: never;
    };
    "/api/machines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Machines */
        get: operations["machines_api_machines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/structures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Structures
         * @description Every lightweight buildable the player placed: foundations, ramps, walls, catwalks.
         *
         *     These are the only record of what was physically BUILT -- they appear in no actor
         *     header, which is why the projection interns them separately as
         *     ``{"classes": [...], "instances": [[class_index, x, y, z, yaw], ...]}`` in centimetres.
         *     Decoded by ``core.saveio.rows``, which is where the guard lives for all ten readers
         *     of these interned tables: a malformed row costs one piece, not the endpoint.
         *
         *     **Rotation is carried, as of schema 12**, and this docstring used to say the opposite
         *     -- the instance transform's quaternion was dropped at extraction and a client could
         *     only draw these axis-aligned, which is why an angled slab came out of the map as a
         *     staircase of squares. ``yaw`` is now the fifth column of a row and comes out as a
         *     ``yaw`` field: degrees about world Z, positive turning +X towards +Y. ``null`` for a
         *     projection cut before 12, which a client must keep drawing axis-aligned rather than
         *     reading as zero.
         *
         *     One thing the projection still does not carry, and it is not invented here:
         *
         *     * **Per-class size.** None of these classes has clearance data, so ``footprint`` is
         *       ``None`` for all eighteen of them. They are all built on the same grid instead,
         *       whose edge ``tile_m`` reports from ``FOUNDATION_M`` so the page does not hardcode 8.
         *
         *     Positions are piece centres: on the reference save consecutive foundations of one
         *     slab sit exactly ``tile_m`` apart.
         *
         *     A world with nothing built answers ``{"structures": [], "count": 0}`` -- an empty
         *     list is a real answer here, unlike a save that could not be read at all.
         *
         *     Sent one row per piece, ungrouped. Measured on the reference world -- 8,347 pieces,
         *     708 KB (610 KB of it before the yaw column) -- which is the same order as
         *     ``/api/collectibles`` already ships (3,455 rows, 547 KB). Grouping into grid cells would halve a
         *     payload that is not the bottleneck and would cost the per-piece class the popup and
         *     the point inspector read.
         */
        get: operations["structures_api_structures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/belts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Belts
         * @description Every conveyor belt and lift, as the polyline it was actually built along.
         *
         *     New in schema 12, and the reason the map drew no belts at all until now: the splines
         *     were decoded by the parser and thrown away at the projection. They arrive interned the
         *     way the structures next door are -- ``{"classes": [...], "segments": [[chain_index,
         *     class_index, [[x, y, z], ...]], ...]}``, world centimetres -- and, like that endpoint,
         *     the legend is resolved here so the page does not have to carry it, and the row is
         *     decoded by ``core.saveio.rows`` so that a malformed segment costs that segment rather
         *     than the network.
         *
         *     **Points are in travel order, input to output.** The save stores them output-first and
         *     the projection reverses them, so a client can draw direction along a run without
         *     knowing that. ``chain`` is the belt chain a piece belongs to -- 1,909 chains over 3,085
         *     pieces on the reference world -- so "the whole run" is a group-by rather than a
         *     geometry problem.
         *
         *     **``curve_m`` is new in schema 15, and it is what makes a curved belt curved.** The points
         *     are the spline's control points and were never the whole spline: the chain trailer stores
         *     two tangents beside each one, the projection dropped them, and a bend therefore arrived as
         *     the chords between its corners -- out by up to 16.4 m of arc on a single piece, measured
         *     against the length the save states for it. One entry per span here, ``null`` where that
         *     span is straight and ``[leave, arrive]`` metres where it is not, so a client draws a cubic
         *     Hermite where there is one and the same two-point line as before where there is not.
         *     ``null`` for the whole field on the 2,119 pieces with no bend anywhere in them.
         *
         *     **A lift is a belt whose top-down polyline is a single point.** All 302 lifts on the
         *     reference save have exactly zero horizontal extent (measured: median *and* maximum
         *     horizontal span 0.0 cm, median rise 4 m), so a map that draws them as lines draws
         *     nothing at all where they are. ``lift`` says which ones, and the client owes them a
         *     glyph instead.
         *
         *     Sent one row per piece, ungrouped, the same posture ``/api/structures`` takes and for
         *     the same reason: the per-piece class is what a popup reads. Measured on the reference
         *     world -- 3,085 pieces, 8,292 points, 562 KB -- which is the same order as the floor
         *     plan beside it (8,347 pieces, 708 KB). The geometry is already only the bends: 2,237 of
         *     the 3,085 pieces are two-point straight lines, 2.7 points per piece overall.
         *
         *     **``attachments`` rides along, and belongs here rather than with the machines.** A
         *     splitter or a merger is a piece of the belt network -- it runs no recipe, draws no power
         *     and is meaningless without the runs either side of it -- so it travels with the runs and
         *     is drawn by the layer that draws them. That is also what keeps it from being drawn twice:
         *     it is in no other payload, so a map with the machines layer on and the belts layer off
         *     shows no splitters at all, which is the honest picture of "these are belt parts".
         *
         *     They carry no spline -- a splitter is a point with a facing, not a route -- so they are a
         *     row shape of their own: where it stands, which way it faces, and what it is. 848 of them
         *     on the reference world -- 481 splitters, 364 mergers, 3 smart splitters -- 170 KB against
         *     the 562 KB of runs they join.
         */
        get: operations["belts_api_belts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipes
         * @description Every fluid pipe, as the polyline it was actually built along, and what it carries.
         *
         *     New in schema 13, and the belts' other half. The geometry was never hidden the way the
         *     belts' was -- a pipe's spline is an ordinary ``mSplineData`` PROPERTY on the pipeline
         *     actor, stored in the actor's own frame and translated back at the projection -- so this
         *     is the same shape one layer down: ``{"classes": [...], "networks": [...], "segments":
         *     [[network_index, class_index, [[x, y, z], ...]], ...]}`` in world centimetres, resolved
         *     here so the page carries no legend, the row decoded by ``core.saveio.rows`` so a
         *     malformed segment costs that segment.
         *
         *     **Each pipe says which fluid it carries**, which is the thing a belt cannot say: the game
         *     keeps an ``FGPipeNetwork`` per connected plumbing system with the fluid on it and its
         *     members listed, so ``fluid`` is the world's own answer rather than an inference from what
         *     the pipe is plugged into. All 503 pipes on the reference world are claimed by one of its
         *     19 networks -- 215 crude oil, 198 water, 55 fuel, 31 heavy oil residue, 4 alumina
         *     solution. ``null`` for a pipe no network claims, which happens on none of them here but
         *     is what an empty or half-built network would give.
         *
         *     **``direction`` is INFERRED, and ``basis`` says from what.** Nothing on a pipe records
         *     which way the fluid goes -- that much of the old refusal stands, and the points are still
         *     in the order the file stores them. But the plumbing AROUND it records a great deal: the
         *     save serialises every fluid coupling, and names a machine's port ``PipeInputFactory`` or
         *     ``PipeOutputFactory``. ``domain/world/flow.py`` reads that graph and declines wherever
         *     more than one answer is consistent. So ``direction`` is ``forward`` along ``points_m``,
         *     ``reverse`` against it, or ``unknown`` -- 365, and 138 unknown, on the reference world --
         *     and ``basis`` is one of:
         *
         *     * ``machine port`` -- this very pipe ends at a port the save TYPES. Barely an inference.
         *     * ``pump`` -- a pump or valve at one end, one-way by construction.
         *     * ``propagated`` -- only the shape of the wider network settles it.
         *     * ``unresolved`` -- and then ``direction`` is ``unknown``. A pipe in a loop, or a trunk
         *       with producers and consumers on both sides, genuinely has no fixed direction.
         *
         *     A client may draw an arrow on the first three and must not on the fourth.
         *
         *     **``curve_m`` rides here too, on exactly the belts' terms.** A pipe's ``mSplineData`` has
         *     carried an ``ArriveTangent`` and a ``LeaveTangent`` beside every ``Location`` the whole
         *     time, and schema 13 dropped them on the grounds that pipes are straight runs and elbows.
         *     They are -- and the six points of an elbow are its corners, not its curve: 166 of this
         *     world's 1,484 spans leave their chord by more than 10 cm and one by 6.6 m, so an elbow drew
         *     as the polygon cutting the corner it was built to round. One entry per span, ``null`` where
         *     the span is straight, ``null`` for all 207 pipes with no bend in them at all.
         *
         *     Sent one row per piece, ungrouped, the posture ``/api/belts`` and ``/api/structures`` both
         *     take. Measured on the reference world -- 503 pipes, 1,987 points, 48 KB -- an order
         *     smaller than the 562 KB of belts beside it, because there are six times fewer of them.
         *     Nothing to thin: 3.9 points a pipe, and they are already only the corners.
         *
         *     Not in here: pumps, junctions, valves and fluid buffers. They carry no spline at all, only
         *     a header position, so they are a different row shape and a different question -- the same
         *     question the belts key leaves open about splitters and mergers.
         */
        get: operations["pipes_api_pipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Storage
         * @description Every storage container and fluid buffer, and what is inside each one.
         *
         *     New in schema 15, and the gap it fills is a specific one. The projection has been able to
         *     say what the player OWNS since schema 11 -- ``inventories["storage"]``, every stack in
         *     every container summed -- and has never been able to say where any of it is. That answers
         *     "have I got enough steel to build that" and is exactly the wrong shape for "where did I
         *     put the steel", which is the question a base with 105 containers spread over 7 km actually
         *     raises. Nothing else carried a container at all: they run no recipe so they were never
         *     machines, draw no power so they are not in the power graph, and are ordinary actors so they
         *     are not lightweight buildables either.
         *
         *     **Which classes, and the one that had to be excluded.** 151 rows on the reference world:
         *     61 Storage Containers and 44 Industrial ones, 6 Personal Storage Boxes, 33 Dimensional
         *     Depot uploaders, the HUB's built-in container and the Blueprint Designer's, and 5 fluid
         *     buffers. NOT the splitters and mergers -- every one of the world's 848 owns a component
         *     literally named ``StorageInventory``, holding the one to three items physically inside the
         *     junction, and a payload built by matching that name would report 848 phantom containers,
         *     draw them a second time over the belt layer that already has them, and count items in
         *     transit as stock. Machine input and output buffers are excluded on the same principle and
         *     are not lost: they are on their own machine's row under ``buffers``, where they mean "this
         *     smelter is starved" rather than "the player owns this".
         *
         *     **Two record shapes, told apart by ``kind``.** A solid container reports ``items`` (biggest
         *     first, resolved to display names, truncated with a ``more`` count), ``slots`` and
         *     ``total``; a fluid buffer reports ``fluid``, ``stored_m3``, ``capacity_m3`` and ``fill``.
         *
         *     **The fluid's identity comes off the plumbing, not off the buffer.** A buffer stores a bare
         *     ``mFluidBox`` float and never names its contents, so the name is taken from the
         *     ``FGPipeNetwork`` that claims it -- the same join, and the same source, ``/api/pipes`` uses
         *     for a pipe's ``fluid``. ``null`` for a buffer no network claims, which happens on none of
         *     the five here.
         *
         *     Small: 151 rows against the 3,085 of ``/api/belts``, and the whole key is 26 KB of
         *     projection. Sent in one payload, ungrouped, the posture every placement endpoint here
         *     takes.
         */
        get: operations["storage_api_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Factories
         * @description Named factories and the coherence-scored proposals for the unnamed rest.
         *
         *     Each row carries ``bbox_m`` -- ``[x_min, y_min, x_max, y_max]`` in metres, game axes
         *     -- alongside its centroid, because a centroid alone cannot frame a viewport. The map
         *     turns a label into a button that flies to its factory, and "fly to the mean of 50
         *     machines" is not the same request as "show me all 50": the first picks a zoom out of
         *     the air, the second is decided by the extent. Computed here rather than client-side
         *     because the client is never sent the anchor machines, only their count.
         *
         *     ``null`` when nothing in the set is still standing -- ``geo.bbox`` refuses to invent
         *     a zero box at the world centre, and so does this. A label whose machines were all
         *     demolished keeps its name and its remembered centroid; what it loses is the ability
         *     to be flown to, which is the honest report.
         *
         *     A proposal whose machines the player has already named is not a proposal: the
         *     clusterer runs over the whole world, so it re-discovers every named factory, and
         *     sending those rows lets a machine-generated recipe string draw itself exactly on
         *     top of the player's own label. Any proposal in which named anchors are the majority
         *     is dropped here; ``index`` stays the position in the full proposal list, so a
         *     ``proposal:N`` selector still resolves to the same cluster in the MCP tools.
         */
        get: operations["factories_api_factories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/floors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Floors View
         * @description What is built, one storey at a time: the floor decomposition of a world.
         *
         *     Nothing in the save says "floor". ``domain.factories.floors`` recovers them from the
         *     geometry -- 4-connected platforms of 8 m foundation cells, then a per-platform cluster
         *     of deck heights -- and every constant it uses was measured before it was written. This
         *     endpoint parses the query, calls it once, and rounds.
         *
         *     **It ships ids, not geometry, and that is the design.** A client already has every
         *     machine, splitter, belt and pipe from the four endpoints above; the one thing it cannot
         *     derive is which floor each of them is on. So a band lists ``machines`` and
         *     ``attachments`` as instance leaves, and a run is keyed by its belt ``chain`` or its pipe
         *     row position -- the joins those payloads already carry. Sending the coordinates again
         *     would double 1.3 MB so that a filter could be applied to the copy.
         *
         *     **The runs are grouped by what they do to a floor**, not listed flat:
         *
         *     * ``same-deck`` -- both ends over one band. 84.8% of belt runs, and the set a floor
         *       filter draws.
         *     * ``connector`` -- the ends are on two different bands. This is how you leave a floor,
         *       and it is where the lifts and risers are.
         *     * ``terrain`` -- neither end is over a deck. 44.5% of pipes, because plumbing hugs the
         *       ground.
         *     * ``mixed`` -- one end on a deck, one on the ground.
         *
         *     **``placements`` is only what did NOT land on a floor.** Things that did are listed by
         *     id inside their own band, so listing them here as well would be the same 1,252 rows
         *     twice. What is here is the three honest ways of not being on a floor: ``exempt`` (a
         *     miner stands on a resource node and a water extractor on water -- by native class, not
         *     by a substring), ``terrain`` (measured against the heightfield) and ``off-deck``.
         *
         *     **``terrain_measured`` says whether the ground was consulted at all.** The 1 m
         *     heightfield is derived from the reader's own game install and most machines have none,
         *     in which case nothing can be in the ``terrain`` group and an empty one would otherwise
         *     read as "nothing is on the ground here".
         *
         *     ``?factory=`` takes a label the player gave a factory, or any selector the MCP tools
         *     take, and narrows the answer to the platforms that factory stands on. ``?platform=`` is
         *     the index this endpoint hands out, which is stable across calls. Either narrows
         *     placements and runs to that footprint -- including the ones underneath it, since "what
         *     is under this deck" is part of the question.
         *
         *     A save too old to carry ``FGLightweightBuildableSubsystem`` is a **200 with a
         *     ``note``**, not an error and not an empty list: the world has floors, this file cannot
         *     show them, and those are different sentences.
         */
        get: operations["floors_view_api_floors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collectibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Collectibles
         * @description Map placements, filtered exactly the way the MCP tool filters them.
         *
         *     ``collect_view`` owns every refusal -- unknown mode, retired group, and the one
         *     that matters here: ``mode=remaining`` needs the generated placement table, and
         *     without it the honest answer is the refusal rather than a shorter list.
         */
        get: operations["collectibles_api_collectibles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Server-sent events: one ``save`` event per observed write, plus keepalives.
         *
         *     The stream carries the trigger, never the payload. A save event says which file
         *     moved and when; the page decides what to refetch. That keeps this endpoint O(1) in
         *     the size of the world and means a browser that missed an event is one refetch, not
         *     one resync, behind.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * FloorBand
         * @description One floor of one platform. See ``_band_json`` for what each field means.
         */
        FloorBand: {
            /** Ordinal */
            ordinal: number;
            /** Top M */
            top_m: number | null;
            /** Low M */
            low_m: number | null;
            /** High M */
            high_m: number | null;
            /** Span M */
            span_m: number | null;
            /** Pieces */
            pieces: number;
            /** Cells */
            cells: number;
            /** Area M2 */
            area_m2: number;
            /** Share */
            share: number;
            /** Minor */
            minor: boolean;
            /** Machines */
            machines: string[];
            /** Attachments */
            attachments: string[];
            /** Machine Count */
            machine_count: number;
            /** Attachment Count */
            attachment_count: number;
        };
        /**
         * FloorCounts
         * @description The shape of the answer before the rows. Nested; see ``FloorReport.counts``.
         */
        FloorCounts: {
            /** Platforms */
            platforms: number;
            /** Bands */
            bands: number;
            /** Runs */
            runs: number;
            /** Violations */
            violations: number;
            /** Placements */
            placements: {
                [key: string]: number;
            };
            /** Membership */
            membership: {
                [key: string]: number;
            };
        };
        /**
         * FloorDeck
         * @description One band, identified. What a run's ``ends`` are made of.
         */
        FloorDeck: {
            /** Platform */
            platform: number;
            /** Ordinal */
            ordinal: number;
            /** Top M */
            top_m: number | null;
        };
        /**
         * FloorPlacement
         * @description One thing that is NOT on a floor, and the reason it is not.
         */
        FloorPlacement: {
            /** Instance Leaf */
            instance_leaf: string;
            /** Cls */
            cls: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** X M */
            x_m: number | null;
            /** Y M */
            y_m: number | null;
            /** Z M */
            z_m: number | null;
            /** Above Terrain M */
            above_terrain_m: number | null;
        };
        /**
         * FloorPlatform
         * @description One 4-connected run of foundation cells, and the bands its tops fall into.
         */
        FloorPlatform: {
            /** Index */
            index: number;
            /** Cells */
            cells: number;
            /** Pieces */
            pieces: number;
            /** Area M2 */
            area_m2: number;
            /** Centre M */
            centre_m: (number | null)[];
            /** Extent M */
            extent_m: (number | null)[];
            /** Clean */
            clean: number;
            /** Label */
            label: string | null;
            /** Slab */
            slab: number | null;
            /** Bands */
            bands: components["schemas"]["FloorBand"][];
        };
        /**
         * FloorRules
         * @description The thresholds the answer was produced with, in the units the answer is in.
         */
        FloorRules: {
            /** Tile M */
            tile_m: number | null;
            /** Cluster Tol M */
            cluster_tol_m: number | null;
            /** Band Eps M */
            band_eps_m: number | null;
            /** Min Band Pieces */
            min_band_pieces: number;
            /** Belt Height M */
            belt_height_m: number | null;
            /** Riser M */
            riser_m: number | null;
            /** Terrain Tol M */
            terrain_tol_m: number;
            /** Minor Share */
            minor_share: number;
        };
        /**
         * FloorRun
         * @description One belt chain or one pipe, keyed by the join the belt and pipe payloads carry.
         *
         *     ``ends`` is always two entries, head then tail, either of which may be ``null`` where
         *     that end is over no deck. A pair rather than a list is what it means, and JSON has no
         *     pair -- so the length is a promise the prose makes and the schema cannot.
         */
        FloorRun: {
            /** Kind */
            kind: string;
            /** Key */
            key: number;
            /** Pieces */
            pieces: number;
            /** Lift */
            lift: boolean;
            /** Rise M */
            rise_m: number | null;
            /** Riser */
            riser: boolean;
            /** Ends */
            ends: (components["schemas"]["FloorDeck"] | null)[];
        };
        /**
         * FloorsResponse
         * @description What ``/api/floors`` sends on a 200. An error is a 4xx with ``{"error": ...}``.
         *
         *     Field order matters here and is the emission order below, because a response_model
         *     serialises in declaration order: reordering these reorders the bytes on the wire.
         */
        FloorsResponse: {
            /** Note */
            note: string | null;
            /** Selection */
            selection: string | null;
            /** Terrain Measured */
            terrain_measured: boolean;
            counts: components["schemas"]["FloorCounts"];
            /** Platforms */
            platforms: components["schemas"]["FloorPlatform"][];
            /** Runs */
            runs: {
                [key: string]: components["schemas"]["FloorRun"][];
            };
            /** Placements */
            placements: {
                [key: string]: components["schemas"]["FloorPlacement"][];
            };
            /** Violations */
            violations: components["schemas"]["FloorRun"][];
            rules: components["schemas"]["FloorRules"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    worlds_api_worlds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    summary_api_summary_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nodes_api_nodes_get: {
        parameters: {
            query?: {
                resource?: string | null;
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_api_inspect_get: {
        parameters: {
            query: {
                x_m: number;
                y_m: number;
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regions_api_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mapimage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mapimage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    maptiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maptiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maptiles_layer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maptiles_layer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    machines_api_machines_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structures_api_structures_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belts_api_belts_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipes_api_pipes_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storage_api_storage_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    factories_api_factories_get: {
        parameters: {
            query?: {
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    floors_view_api_floors_get: {
        parameters: {
            query?: {
                factory?: string | null;
                platform?: number | null;
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collectibles_api_collectibles_get: {
        parameters: {
            query?: {
                group?: string | null;
                mode?: string;
                near?: string | null;
                save?: string | null;
                world?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
