/* The build, and the one thing about it that is not Vite's default: where it writes.
 *
 * The output directory IS the directory the Python package serves. `interfaces/web/app.py`
 * mounts `static/` at `/` and knows nothing about this project, so a build lands the page
 * exactly where a fresh clone with no Node expects to find it -- which is the whole point:
 * the built bundle is committed as a generated artifact, and Node is needed only to CHANGE
 * the frontend, never to run it.
 *
 * `emptyOutDir` is on, and it is why nothing hand-written may live in `static/` any more.
 * Every file the server needs is produced here: the page from `index.html`, the bundle and
 * its stylesheet from `src/`, Leaflet's BSD-2-Clause text from `public/`. A file dropped
 * into `static/` by hand survives exactly until the next build.
 */

import { defineConfig, type Plugin } from "vite";

/* Node's own global, declared rather than pulled in with `@types/node`. This file runs under
 * Node and the rest of `src/` runs in a browser; installing the Node types to satisfy one
 * line would put `require`, `Buffer` and `process` in scope for the whole program, where
 * every one of them is a mistake waiting to type-check. */
declare const process: { env: Record<string, string | undefined> };

/* Stamped into every generated file, and asserted by ``tests/test_architecture.py``.
 *
 * No timestamp and no version in it, deliberately: the bundle is committed, so anything
 * that changed on a rebuild-with-no-source-change would make the artifact churn in git and
 * turn its history into noise. What the marker has to say is only "this file is output",
 * and that sentence is the same every time.
 *
 * The Leaflet line is the third of the three places its licence is honoured, and it is here
 * because the minifier strips the library's own `@preserve` header: `vendor/LEAFLET-LICENSE`
 * ships next to the bundle, the page says so in a comment, and the artifact itself now names
 * what is compiled into it. BSD-2-Clause asks for the notice to travel with the binary form,
 * and a reader who opens only this file should not have to go looking. */
const BANNER = [
  "GENERATED by Vite from src/satisfactory_mcp/interfaces/web/frontend/ -- do not edit.",
  "Edit the TypeScript there and run `npm ci && npm run build`; see frontend/README.md.",
  "Bundles Leaflet 1.9.4 (c) 2010-2023 Vladimir Agafonkin, (c) 2010-2011 CloudMade,",
  "BSD-2-Clause -- full text in vendor/LEAFLET-LICENSE beside this file.",
];

/* The marker, injected after minification rather than through `output.banner`.
 *
 * esbuild's minifier runs over the chunk and strips comments that are not legal comments,
 * and the exact interleaving of that pass with Rollup's banner hook is an implementation
 * detail this file should not be betting the guard test on. Writing the string into the
 * finished chunk in `generateBundle` is the one place nothing runs after. */
function banner(): Plugin {
  return {
    name: "build-banner",
    apply: "build",
    enforce: "post",
    generateBundle(_options, bundle) {
      for (const file of Object.values(bundle)) {
        if (file.type === "chunk") {
          file.code = `/* ${BANNER.join("\n * ")} */\n${file.code}`;
        } else if (file.fileName.endsWith(".css") && typeof file.source === "string") {
          file.source = `/* ${BANNER.join("\n * ")} */\n${file.source}`;
        }
      }
    },
    transformIndexHtml(html) {
      return `<!--\n  ${BANNER.join("\n  ")}\n-->\n${html}`;
    },
  };
}

export default defineConfig({
  // Relative asset URLs, as the hand-written page used: the app is mounted at `/` today,
  // and a page whose own links do not depend on that is a page that survives being mounted
  // anywhere else.
  base: "./",
  plugins: [banner()],
  build: {
    outDir: "../static",
    emptyOutDir: true,
    // Stable names, no content hash. The bundle is COMMITTED, so a hash in the filename
    // would add one file and delete another on every frontend change and leave the artifact
    // with no readable history at all. Cache busting is `StaticFiles`' ETag instead, which
    // revalidates on a name that does not move.
    rollupOptions: {
      output: {
        entryFileNames: "app.js",
        chunkFileNames: "chunk-[name].js",
        assetFileNames: (info) =>
          info.names?.some((n) => n.endsWith(".css")) ? "app.css" : "assets/[name][extname]",
      },
    },
  },
  server: {
    proxy: {
      /* Everything the page fetches, straight through to a running `satisfactory-mcp-web`.
       *
       * `/api/events` is Server-Sent Events, so the one thing this must not do is buffer:
       * a proxy that collects a response body before forwarding it turns a live stream into
       * a page that hangs on the first save. Vite's proxy streams and adds no compression of
       * its own, which is why there is nothing to configure here -- and frontend/README.md
       * says how that was measured rather than assumed.
       *
       * The port is `satisfactory-mcp-web`'s own default. The override exists because the
       * server is sometimes already running somewhere else, and because pointing a dev
       * session at a throwaway instance beats pointing it at the one someone is playing
       * against. */
      "/api": {
        target: process.env.SATISFACTORY_MCP_WEB || "http://127.0.0.1:8712",
        changeOrigin: false,
        ws: false,
      },
    },
  },
});
